name: Update Dependencies with Multi-Gitter

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - develop
      - main

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Install multi-gitter
        run: go install github.com/lindell/multi-gitter@latest

      - name: Get PR details
        env:
          HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_ENV
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      - name: Update script with PR details
        run: |
          sed -i 's/VERSION=.*/VERSION=${{ env.COMMIT_SHA }}/' .github/config/multi-gitter-config
          sed -i 's/HEAD_BRANCH=.*/HEAD_BRANCH=${{ env.HEAD_BRANCH }}/' .github/scripts/update-version.sh
          sed -i 's/BASE_BRANCH=.*/BASE_BRANCH=${{ env.BASE_BRANCH }}/' .github/scripts/update-version.sh

      - name: Run multi-gitter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: |

          multi-gitter run .github/scripts/update-version.sh --dry-run --token $GITHUB_TOKEN  --config .github/config/multi-gitter-config   

